// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package test

import (
	"github.com/chandraekap/fita-backend-test/internal/sales"
	"github.com/chandraekap/fita-backend-test/internal/sales/mock"
	"github.com/google/wire"
)

// Injectors from wire.go:

func BuildTestContainer() *TestContainer {
	data := mock.InitData()
	v := data.Carts
	cartRepository := mock.NewCartRepository(v)
	v2 := data.Promos
	promotionRepository := mock.NewPromotionRepository(v2)
	promotionItemFactory := sales.NewPromotionItemFactory()
	checkoutService := sales.NewCheckoutService(cartRepository, promotionRepository, promotionItemFactory)
	promotionItemBuy2Free1 := sales.NewPromotionItemBuy2Free1()
	promotionItemDiscount10Percent := sales.NewPromotionItemDiscount10Percent()
	promotionItemFreeRaspberry := sales.NewPromotionItemFreeRaspberry()
	testContainer := NewTestContainer(checkoutService, promotionItemBuy2Free1, promotionItemDiscount10Percent, promotionItemFreeRaspberry)
	return testContainer
}

// wire.go:

var salesSet = wire.NewSet(mock.InitData, wire.FieldsOf(new(*mock.Data), "Carts", "Promos"), mock.NewCartRepository, wire.Bind(new(sales.CartRepository), new(*mock.CartRepository)), mock.NewPromotionRepository, wire.Bind(new(sales.PromotionRepository), new(*mock.PromotionRepository)), sales.NewPromotionItemFactory, sales.NewCheckoutService, sales.NewPromotionItemBuy2Free1, sales.NewPromotionItemDiscount10Percent, sales.NewPromotionItemFreeRaspberry)
